# Main configuration file for mkdocs generation of klipper3d.org website

# Note that the build-translations.sh script expects a certain file
# layout.  See that script and the README file for more details.

# Site and directory configuration
site_name: BIGTREETECH documentation
repo_url: https://github.com/z1996xm/BIGTREETECH
repo_name: z1996xm/BIGTREETECH
edit_uri: blob/main/docs/
use_directory_urls: False
docs_dir: '../'
site_dir: '../../site/'

# Custom markdown dialect settings
markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 6
  - attr_list
  - mdx_partial_gfm
  - mdx_truly_sane_lists
  - mdx_breakless_lists
plugins:
  search:
    lang: en
  mkdocs-simple-hooks:
    hooks:
      on_page_markdown: "docs._biqumkdocs.mkdocs_hooks:transform"
  exclude:
    glob: "README.md"

# Website layout configuration (using mkdocs-material theme)
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
      #- navigation.tabs
      #- navigation.expand
      - navigation.top
      # if enabled, the TOC doesn't work for some pages
      # - toc.integrate
      - search.suggest
      - search.highlight
      - search.share
  language: en
extra_css:
  - _biqumkdocs/css/extra.css

# Site usage statistics
extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#site-search-tracking
  analytics:
    provider: google
    property: UA-138371409-1
  # Language Selection
  alternate: # 由上面那个i18n插件提供的多语言功能，这个似乎就不需要了。 这个是官方文档的例子，但是官方没有提供很详细的例子，所以我也不知道怎么用。
    - name: English
      link: /en/ 
      lang: en
    - name: Chinese
      link: /zh_Hans/
      lang: zh
  # alternate:
  #   - name: English
  #     link: /
  #     lang: en

nav:
  # - Home: https://z1996xm.github.io/BIGTREETECH
  - BTT: 
    - HDMI5:
      - HDMI5.md
  - BIQU: 
    - HDMI7: 
      - HDMI7.md

