name: biqumkdocs deploy(test)
on:
  push:
    branches:
      - translations
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/biqumkdocs-deploy-test.yaml
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/_biqumkdocs/mkdocs-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r docs/_biqumkdocs/mkdocs-requirements.txt
      - name: Remove reduntant files
        run: rm -rf docs/locales
      - name: Build MkDocs Pages
        run: docs/_biqumkdocs/build-translations.sh
